export const SET_LOADING = 'SET_LOADING';
export const LOAD_ARTICLES = 'LOAD_ARTICLES';
export const UPDATE_SORT = 'UPDATE_SORT';
export const SORT_ARTICLES = 'SORT_ARTICLES';

export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLE = 'GET_ARTICLE';
export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';

export const BOOKMARK_ITEM = 'BOOKMARK_ITEM';
export const UNBOOKMARK_ITEM = 'UNBOOKMARK_ITEM';
export const GET_BOOKMARK_ITEMS = 'GET_BOOKMARK_ITEMS';
