export const FETCH_ARTICLES_BEGIN = 'FETCH_ARTICLES_BEGIN';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';

export const FETCH_ARTICLE_BEGIN = 'FETCH_ARTICLE_BEGIN';
export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_ERROR = 'FETCH_ARTICLE_ERROR';

export const SEARCH_ARTICLES_BEGIN = 'SEARCH_ARTICLES_BEGIN';
export const SEARCH_ARTICLES_SUCCESS = 'SEARCH_ARTICLES_SUCCESS';
export const SEARCH_ARTICLES_ERROR = 'SEARCH_ARTICLES_ERROR';

export const FETCH_SPORTS = 'FETCH_SPORTS';

export const FETCH_BOOKMARK_ITEMS = 'FETCH_BOOKMARK_ITEMS';
export const BOOKMARK_ITEM = 'BOOKMARK_ITEM';
export const UNBOOKMARK_ITEM = 'UNBOOKMARK_ITEM';

export const HANDLE_SEARCH = 'HANDLE_SEARCH';
export const HANDLE_SORT = 'HANDLE_SORT';
export const HANDLE_PAGINATION = 'HANDLE_PAGINATION';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';
