export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_SPORTS = 'FETCH_SPORTS';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';

export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
export const HANDLE_SEARCH = 'HANDLE_SEARCH';

export const HANDLE_PAGINATION = 'HANDLE_PAGINATION';
export const HANDLE_INFINITE_SCROLL = 'HANDLE_INFINITE_SCROLL';
export const HANDLE_SORT = 'HANDLE_SORT';

export const FETCH_BOOKMARK_ITEMS = 'FETCH_BOOKMARK_ITEMS';
export const BOOKMARK_ITEM = 'BOOKMARK_ITEM';
export const UNBOOKMARK_ITEM = 'UNBOOKMARK_ITEM';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const SET_LOADING = 'SET_LOADING';
