export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_MINOR = 'GET_ARTICLES_MINOR';
export const SEARCH_ARTICLES = 'SEARCH_ARTICLES';
export const GET_ARTICLE = 'GET_ARTICLE';

export const GET_BOOKMARK_ITEMS = 'GET_BOOKMARK_ITEMS';
export const BOOKMARK_ITEM = 'BOOKMARK_ITEM';
export const UNBOOKMARK_ITEM = 'UNBOOKMARK_ITEM';

export const HANDLE_PAGINATION = 'HANDLE_PAGINATION';
export const HANDLE_SEARCH = 'HANDLE_SEARCH';
export const HANDLE_SORT = 'HANDLE_SORT';
export const SORT_ARTICLES = 'SORT_ARTICLES';

export const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR';

export const SET_LOADING = 'SET_LOADING';
